version: '3'
services:
  fsmud:
    build: .
    ports:
     - "8010:8010"
    depends_on:
     - "fsdb"
    environment:
     - GIN_MODE=debug
     - MONGODB_CONNECTION_STRING=mongodb://fsdb:27017
     - MONGODB_DATABASE=fsmud
     - MONGODB_USER=fsmud
     - MONGODB_PASSWORD=fsmud
     - AUTH0_AUDIENCE=http://talesofapirate.com/dnd/api
     - AUTH0_DOMAIN=https://owndnd.eu.auth0.com/
     - AUTH0_WK_JWKS=https://owndnd.eu.auth0.com/.well-known/jwks.json
     - ADMIN_USER=admin
     - ADMIN_PASSWORD=admin
  fsdb:
    image: "mongo:4.2.6"
    ports:
     - "27017:27017"
    volumes:
        - ~/volumes/fsmud/db:/data/db
